-- Migration: 0006_content_seo_and_topic_tagging
-- Created:   2026-07-12
-- Author:    Neo (database specialist)
--
-- Follow-on to 20260710000000_content_engine_schema.sql and
-- 20260711000000_viral_trend_scan_tracking.sql. Adds what the 7-piece SEO
-- build needs (approved by Peter after Oracle's planning/review passes):
--
--   1. content_items.published_url — the live URL, set once by Peter via a
--      "Mark as Published" action after a post actually goes live. UNIQUE so
--      the upcoming 185-post historical backfill script can safely check
--      "is this URL already in the table?" before inserting — making the
--      backfill idempotent (safe to re-run, and safe to run alongside new
--      posts being marked published) without ever creating a duplicate row
--      for the same URL.
--   2. content_items.seo_title — a short (~55-60 char), literal,
--      keyword-forward title, generated by the AI on every new draft and
--      every revision. Distinct from the existing `title` column, which
--      stays the punchy on-page headline in Peter's established voice.
--      Mirrors how `meta_description` already works on this table.
--   3. content_items.faq_schema — a FAQPage schema.org JSON-LD object,
--      built server-side by the app (Q's concern, not this migration's).
--   4. content_item_topics (new table) — many-to-many link between a
--      content item and the compliance_topics it's about (12 real legal
--      topics). Populated for BOTH new AI-drafted posts and the 185
--      backfilled historical posts, so internal-linking logic
--      (getInternalLinkCandidates()-style: "find items sharing a topic")
--      works identically for old and new content. Deliberately separate
--      from content_item_compliance_claims, which means something stronger
--      ("this piece cited this specific legal claim as grounding") —
--      backfilled posts are link targets only and must never be mistaken
--      for a grounding source.
--
-- Design notes:
--   - published_url is nullable (most rows haven't been published yet) but
--     UNIQUE — Postgres allows unlimited NULLs under a UNIQUE constraint,
--     so this is safe for the many draft/unpublished rows.
--   - content_item_topics is a plain join table (content_item_id, topic_id),
--     matching this schema's existing pattern for many-to-many links —
--     content_item_compliance_claims (in 20260710000000) is the direct
--     precedent: same shape, same ON DELETE behavior (CASCADE on the
--     content_item side, RESTRICT on the referenced-topic side so a topic
--     in use can't be silently deleted out from under linked content). A
--     TEXT[] array of topic_keys directly on content_items was considered
--     and rejected: it would drop referential integrity (no guarantee a
--     stored key still matches a real compliance_topics row), it would be
--     the only place in this schema doing many-to-many that way, and the
--     query Q needs — "every content_item sharing at least one topic with
--     a given set of topic_ids" — is a plain indexed join against this
--     table (`WHERE topic_id IN (...)`), no less simple than an array
--     overlap (`&&`) query would have been.
--   - No new column was added for the backfilled posts' short 1-3 sentence
--     summary. The existing `content_items.body` column is reused as-is:
--     it has no length constraint, and every code path that reads it
--     (projects/content-review/server.js's draft-detail view via
--     lib/highlight.js's renderDraftBody()/countReviewFlags(), and
--     content-engine's lib/draft.js and lib/revise.js) either just
--     displays whatever text is there or regex-scans it for a
--     "[NEEDS HUMAN REVIEW: ...]" flag — nothing assumes `body` is always
--     full-length. revise.js in particular (the one place `body` feeds
--     back into an AI call) only runs against items whose status is
--     'needs_changes', which backfilled rows — inserted directly with
--     status='published' — will never pass through. A COMMENT ON COLUMN is
--     added below to document the dual meaning for future readers.
--
-- RLS is enabled on the new table and locked down by default, matching
-- every other table in this schema — no permissive policy is added here.
--
-- Rollback: see the DROP section at the bottom of this file.
-- ============================================================


-- ============================================================
-- ALTER TABLE: content_items
-- Adds the three SEO-build columns: published_url (unique, for idempotent
-- backfill), seo_title (distinct from the on-page `title`), and faq_schema
-- (FAQPage JSON-LD, built server-side).
-- ============================================================

ALTER TABLE content_items
  ADD COLUMN published_url TEXT,     -- live URL; set once via "Mark as Published"; NULL until then
  ADD COLUMN seo_title     TEXT,     -- ~55-60 char literal/keyword-forward title, distinct from `title`
  ADD COLUMN faq_schema    JSONB;    -- FAQPage schema.org JSON-LD object; NULL if not applicable

ALTER TABLE content_items
  ADD CONSTRAINT uq_content_items_published_url UNIQUE (published_url);

COMMENT ON COLUMN content_items.published_url IS
  'Live URL, set once by Peter via "Mark as Published" after the post actually goes live. UNIQUE (multiple NULLs allowed) so the historical backfill script can check for an existing row by URL before inserting, making it safe to re-run.';

COMMENT ON COLUMN content_items.seo_title IS
  'Short (~55-60 char), literal, keyword-forward title for search engines. Generated by the AI on every new draft and revision. Distinct from `title`, which stays the on-page headline in Peter''s established voice.';

COMMENT ON COLUMN content_items.faq_schema IS
  'FAQPage schema.org JSON-LD object, built server-side (JSON.stringify on a real object). NULL when not applicable to this content item.';

COMMENT ON COLUMN content_items.body IS
  'Draft/final content. For normally-drafted items this is the full long-form text. For the 185 backfilled historical posts, this deliberately holds only a short 1-3 sentence summary instead of full article text — those rows are internal-link targets only, never a source of facts for the AI, and keeping `body` short on those rows keeps that boundary visible just by looking at the data. No column-level length constraint either way.';


-- ============================================================
-- TABLE: content_item_topics
-- What it stores: which of the 12 compliance_topics a content item is
-- about — for both new AI-drafted posts and the 185 backfilled historical
-- posts, so internal-linking match logic works identically for old and new
-- content. This is NOT the same relationship as
-- content_item_compliance_claims: that table means "this piece cited this
-- specific legal claim as grounding." This table only means "this piece is
-- about this topic" — backfilled posts get rows here but never in
-- content_item_compliance_claims, since they cite no claims.
-- RLS: enabled, locked by default.
-- ============================================================

CREATE TABLE content_item_topics (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  content_item_id   UUID NOT NULL REFERENCES content_items(id) ON DELETE CASCADE,
  topic_id          UUID NOT NULL REFERENCES compliance_topics(id) ON DELETE RESTRICT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_content_item_topic UNIQUE (content_item_id, topic_id)
);

ALTER TABLE content_item_topics ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_content_item_topics_content_item_id ON content_item_topics(content_item_id);
CREATE INDEX idx_content_item_topics_topic_id        ON content_item_topics(topic_id);


-- ============================================================
-- ROLLBACK (run these statements in order to undo this migration)
-- ============================================================
--
-- DROP TABLE IF EXISTS content_item_topics;
--
-- ALTER TABLE content_items DROP CONSTRAINT IF EXISTS uq_content_items_published_url;
-- ALTER TABLE content_items DROP COLUMN IF EXISTS faq_schema;
-- ALTER TABLE content_items DROP COLUMN IF EXISTS seo_title;
-- ALTER TABLE content_items DROP COLUMN IF EXISTS published_url;
--
-- Note: the COMMENT ON COLUMN content_items.body added above documents the
-- backfill's reuse of the existing column; there is no column to drop for
-- it, and the comment itself does not need to be reverted, but for
-- completeness: COMMENT ON COLUMN content_items.body IS NULL; would clear it.
--
-- ============================================================
